name: BDXI Telegram IPTV Auto Update

on:
  workflow_dispatch:

  schedule:
    - cron: "*/10 * * * *"

jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Update Telegram Playlist
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python bot.py

      - name: Save Bot State
        run: |
          git config user.name "BDXI IPTV Bot"
          git config user.email "actions@github.com"

          git add state.json

          if git diff --cached --quiet; then
            echo "No state changes."
          else
            git commit -m "Update Telegram bot state"
            git push
          fi
